# Generated by Django 5.1.3 on 2024-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nic',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='problem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
