# Generated by Django 4.2.16 on 2024-11-25 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0032_alter_medicine_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 25, 16, 30, 41, 319238, tzinfo=datetime.timezone.utc)),
        ),
    ]
